name: Build ISO

on:
  push:
      paths-ignore:
      - '**.md'
  pull_request:
        paths-ignore:
        - '**.md'
  

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: panchajanya1999/archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v3          
      
      - name: Install ArchISO
        run: |
          pacman -Sy
          pacman --noconfirm -S git archiso

      - name: Build ISO File
        run: |
          mkarchiso -v .
          find out/

      - uses: actions/upload-artifact@v2
        with:
          name: dragoonlinux
          path: out/*.iso
